/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecohass;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static ecohass.NuevoArbol.ps;
import static ecohass.NuevoArbol.conexion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaime
 */
public class EdicionDeArbol extends javax.swing.JFrame {

    static ResultSet rr;
    static int ids;
    static int ruta;

    /**
     * Creates new form EdicionDeArbol
     *
     * @param id
     */
    public EdicionDeArbol(int id, int pr) {
        initComponents();
        ids = id;
        ruta = pr;
        j2.setText("Arbol #" + id);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLayout(null);
        j.setBounds(0, 0, (int) screenSize.getWidth(), (int) screenSize.getHeight());
        ImageIcon icn = new ImageIcon(getClass().getResource("/imagenes/otrofondo.jpeg"));
        Icon im = new ImageIcon(icn.getImage().getScaledInstance(j.getWidth(), j.getHeight(), Image.SCALE_DEFAULT));
        j.setIcon(im);
    }

    private EdicionDeArbol() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        zona = new javax.swing.JCheckBox();
        altura = new javax.swing.JCheckBox();
        ancho = new javax.swing.JCheckBox();
        edad = new javax.swing.JCheckBox();
        nivel = new javax.swing.JCheckBox();
        siembra = new javax.swing.JCheckBox();
        foto = new javax.swing.JCheckBox();
        total = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ECOHASS - FINCA LA ESPERANZA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        j2.setForeground(new java.awt.Color(0, 0, 153));
        j2.setText("jLabel1");
        j2.setOpaque(true);
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 160, -1));

        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jButton10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checked.png"))); // NOI18N
        jButton10.setText("Actualizar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        zona.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        zona.setText("Zona");
        getContentPane().add(zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        altura.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        altura.setText("Altura");
        getContentPane().add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        ancho.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        ancho.setText("Ancho");
        getContentPane().add(ancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        edad.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        edad.setText("Edad");
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        nivel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        nivel.setText("Nivel de crecimiento");
        getContentPane().add(nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        siembra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        siembra.setText("Fecha de siembra");
        getContentPane().add(siembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        foto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        foto.setText("Fecha de foto");
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        total.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        total.setText("Total producido");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona los campos a editar");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        j.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/otrofondo.jpeg"))); // NOI18N
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /* try {
            Process p = Runtime.getRuntime().exec("C:\\xampp\\xampp_stop");
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_formWindowClosing

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            Perfil p = new Perfil("a", ids, ruta);
            this.dispose();
            p.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EdicionDeArbol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Object[] zonas = {"zona 1", "zona 2", "zona 3", "zona 4", "zona 5"};
        Connection c = conexion();
        try {
            if (!(zona.isSelected() || altura.isSelected() || ancho.isSelected() || edad.isSelected() || nivel.isSelected() || siembra.isSelected() || foto.isSelected() || total.isSelected())) {
                JOptionPane.showMessageDialog(null, "No se seleccionó ningún campo", "Alerta", JOptionPane.WARNING_MESSAGE);
            } else {
                if (zona.isSelected()) {
                    Object opcion = JOptionPane.showInputDialog(null, "Selecciona la nueva zona", "Cambio de zona", JOptionPane.QUESTION_MESSAGE, null, zonas, zonas[0]);
                    if (!(opcion == null)) {
                        ps = c.prepareStatement("UPDATE aguacates SET zona = ? WHERE id=" + ids);
                        ps.setString(1, opcion.toString());
                        int e = ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    zona.setSelected(false);
                }
                if (altura.isSelected()) {
                    String g = JOptionPane.showInputDialog(null, "Digite la nueva altura");
                    if (!(g == null)) {
                        System.out.println(g);
                        ps = c.prepareStatement("UPDATE aguacates SET altura = ? WHERE id=" + ids);
                        ps.setString(1, g);
                        int e = ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    altura.setSelected(false);
                }
                if (ancho.isSelected()) {
                    String g2 = JOptionPane.showInputDialog(null, "Digite el nuevo ancho");
                    if (!(g2 == null)) {
                    ps = c.prepareStatement("UPDATE aguacates SET ancho = ? WHERE id=" + ids);
                    ps.setString(1, g2);
                    int e = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    ancho.setSelected(false);
                }
                if (edad.isSelected()) {
                    String g3 = JOptionPane.showInputDialog(null, "Digite la nueva edad");
                    if (!(g3 == null)) {
                    ps = c.prepareStatement("UPDATE aguacates SET edad = ? WHERE id=" + ids);
                    ps.setString(1, g3);
                    int e = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    edad.setSelected(false);
                }
                if (nivel.isSelected()) {
                    String g4 = JOptionPane.showInputDialog(null, "Digite el nivel de crecimiento");
                    if (!(g4 == null)) {
                    ps = c.prepareStatement("UPDATE aguacates SET niveldecrecimiento = ? WHERE id=" + ids);
                    ps.setString(1, g4);
                    int e = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    nivel.setSelected(false);
                }
                if (siembra.isSelected()) {
                    String g5 = JOptionPane.showInputDialog(null, "Digite la fecha de siembra");
                    if (!(g5 == null)) {
                    ps = c.prepareStatement("UPDATE aguacates SET fechasiembra = ? WHERE id=" + ids);
                    ps.setString(1, g5);
                    int e = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    siembra.setSelected(false);
                }
                if (foto.isSelected()) {
                    String g6 = JOptionPane.showInputDialog(null, "Digite la fecha de la foto actual");
                    if (!(g6 == null)) {
                    ps = c.prepareStatement("UPDATE aguacates SET fechafoto = ? WHERE id=" + ids);
                    ps.setString(1, g6);
                    int e = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    foto.setSelected(false);
                }
                if (total.isSelected()) {
                    String g7 = JOptionPane.showInputDialog(null, "Digite el total producido");
                    if (!(g7 == null)) {
                    ps = c.prepareStatement("UPDATE aguacates SET totalproducido = ? WHERE id=" + ids);
                    ps.setString(1, g7);
                    int e = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha completado la actualización.");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se llevó a cabo la actualización");
                    }
                    total.setSelected(false);
                }
                
            }

        } catch (SQLException | NullPointerException ex) {
            Logger.getLogger(EdicionDeArbol.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se llevó a acabo la actualización.");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionDeArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionDeArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionDeArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionDeArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionDeArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox altura;
    private javax.swing.JCheckBox ancho;
    private javax.swing.JCheckBox edad;
    private javax.swing.JCheckBox foto;
    private javax.swing.JLabel j;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox nivel;
    private javax.swing.JCheckBox siembra;
    private javax.swing.JCheckBox total;
    private javax.swing.JCheckBox zona;
    // End of variables declaration//GEN-END:variables
}
