/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecohass;

import static ecohass.NuevoArbol.conexion;
import static ecohass.NuevoArbol.existencia;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaime
 */
public class Inicio extends javax.swing.JFrame {

    int pass;
    Connection c = conexion();

    public Inicio(int proveniencia) {
        initComponents();

        pass = proveniencia;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLayout(null);
        j.setBounds(0, 0, (int) screenSize.getWidth(), (int) screenSize.getHeight());
        ImageIcon icn = new ImageIcon(getClass().getResource("/imagenes/ff.jpeg"));
        Icon im = new ImageIcon(icn.getImage().getScaledInstance(j.getWidth(), j.getHeight(), Image.SCALE_DEFAULT));
        j.setIcon(im);
        this.setExtendedState(MAXIMIZED_BOTH);
        jButton1.setBounds(10, (int)(this.getHeight()*0.9),(int)(this.getWidth()*0.1) , (int)(this.getHeight()*0.1));
        /*j.setBounds(0, 0, screenSize.width, screenSize.height);
        ImageIcon icn = new ImageIcon(getClass().getResource("/imagenes/ff.jpeg"));
        Icon im = new ImageIcon(icn.getImage().getScaledInstance(j.getWidth(), j.getHeight(), Image.SCALE_DEFAULT));
        j.setIcon(im);*/
        Component add;
        add = this.add(j);
        jButton1.setBounds(10, 650, 200, 50);
    }

    private Inicio() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        a = new javax.swing.JButton();
        t = new javax.swing.JButton();
        uno = new javax.swing.JRadioButton();
        Todos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        j = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ECOHASS-FINCA LA ESPERANZA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avocado.png"))); // NOI18N
        a.setText("Aguacates");
        a.setToolTipText("Haz click para ver información relacionada con los aguacates");
        a.setBorder(null);
        a.setBorderPainted(false);
        a.setContentAreaFilled(false);
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 130, 300, 140));

        t.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tomato.png"))); // NOI18N
        t.setText("Tomates de arbol");
        t.setToolTipText("Haz click para ver información relacionada con los tomates de arbol");
        t.setBorderPainted(false);
        t.setContentAreaFilled(false);
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        buttonGroup1.add(uno);
        uno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uno.setText("Consulta de un solo arbol");
        uno.setMaximumSize(new java.awt.Dimension(190, 25));
        uno.setMinimumSize(new java.awt.Dimension(190, 25));
        getContentPane().add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        buttonGroup1.add(Todos);
        Todos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Todos.setText("Consulta general");
        getContentPane().add(Todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Finca la esperanza");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 130, 50));

        j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ff.jpeg"))); // NOI18N
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        if (uno.isSelected() || Todos.isSelected()) {
            if (uno.isSelected()) {
                boolean b = true;
                try {
                    do {
                        int arbol;
                        arbol = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el id del arbol"));
                        if (existencia(Integer.toString(arbol))) {
                            b = false;
                            Perfil p = new Perfil("a", arbol, pass);
                            p.setVisible(true);
                            this.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "El arbol " + arbol + " no ha sido registrado.");
                        }
                    } while (b == true);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Debe digitar un número valido");
                } catch (SQLException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                if (Todos.isSelected()) {
                    try {
                        VistaGeneral v;
                        v = new VistaGeneral("a", pass);
                        v.setVisible(true);
                        this.setVisible(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar si la consulta es individual o general");
        }

    }//GEN-LAST:event_aMouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed

    }//GEN-LAST:event_aActionPerformed

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        if (uno.isSelected() || Todos.isSelected()) {

            if (uno.isSelected()) {
                boolean b = true;
                try {
                    while (b == true) {
                        int arbol;
                        arbol = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el id del arbol"));
                        if (arbol < 3000 && arbol > 0) {
                            b = false;
                            Perfil p = new Perfil("t", arbol, pass);
                            p.setVisible(true);
                            this.setVisible(false);
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Debe digitar un numero valido");
                } catch (SQLException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                if (Todos.isSelected()) {
                    try {
                        VistaGeneral v;
                        v = new VistaGeneral("t", pass);
                        v.setVisible(true);
                        this.setVisible(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar si la consulta es individual o general");
        }
    }//GEN-LAST:event_tMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (pass == 1) {
            menu l = new menu();
            l.setVisible(true);
        } else {
            Login l = new Login();
            l.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /*try {
            Process p = Runtime.getRuntime().exec ("C:\\xampp\\xampp_stop");
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Todos;
    private javax.swing.JButton a;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton t;
    private javax.swing.JRadioButton uno;
    // End of variables declaration//GEN-END:variables
}
