/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecohass;

import static ecohass.Administrador.conexion;
import static ecohass.Administrador.fechactual;
import static ecohass.Administrador.ps;
import static ecohass.Administrador.ps2;
import static ecohass.NuevoArbol.AbrirArchivo;
import static ecohass.NuevoArbol.ci;
import static ecohass.NuevoArbol.entrada;
import static ecohass.NuevoArbol.existencia;
import static ecohass.NuevoArbol.hp;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jaime
 */
public class NuevoArbol2 extends javax.swing.JFrame {

    /**
     * Creates new form NuevoArbol2
     */
    public NuevoArbol2() {
        initComponents();
        ImageIcon icn = new ImageIcon(getClass().getResource("/imagenes/u.jpeg"));
        Icon im = new ImageIcon(icn.getImage().getScaledInstance(j.getWidth(), j.getHeight(), Image.SCALE_DEFAULT));
        j.setIcon(im);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechafoto = new com.toedter.calendar.JDateChooser();
        fotico = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fs = new com.toedter.calendar.JDateChooser();
        tp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nc = new javax.swing.JTextField();
        zona = new javax.swing.JComboBox<>();
        edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ancho = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        check5 = new javax.swing.JCheckBox();
        check6 = new javax.swing.JCheckBox();
        check7 = new javax.swing.JCheckBox();
        check8 = new javax.swing.JCheckBox();
        check9 = new javax.swing.JCheckBox();
        j = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel1.setText("Registro de nuevo Arbol");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel2.setText("Registro de nuevo Arbol");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel3.setText("Registro de nuevo Arbol");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        id.setEnabled(false);
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 120, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel9.setText("FECHA DE LA FOTO");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 180, -1));

        fechafoto.setEnabled(false);
        getContentPane().add(fechafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 120, -1));

        fotico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(fotico, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 160, 200));

        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2.setText("CARGAR FOTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 170, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("FECHA DE SIEMBRA");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 180, -1));

        fs.setEnabled(false);
        getContentPane().add(fs, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 140, 30));

        tp.setEnabled(false);
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 140, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("TOTAL PRODUCIDO");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 180, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("NIVEL DE CRECIMIENTO");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 220, -1));

        nc.setEnabled(false);
        nc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncActionPerformed(evt);
            }
        });
        getContentPane().add(nc, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 140, 30));

        zona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------", "ZONA 1", "ZONA 2", "ZONA 3", "ZONA 4", "ZONA 5" }));
        zona.setEnabled(false);
        getContentPane().add(zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, 30));

        edad.setEnabled(false);
        edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadKeyTyped(evt);
            }
        });
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 120, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel6.setText("EDAD");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 60, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel8.setText("ZONA");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel10.setText("ID");
        jLabel10.setToolTipText("Número del árbol en el inventario");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, 20));

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel11.setText("ALTURA");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 80, 20));

        altura.setEnabled(false);
        getContentPane().add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel12.setText("ANCHO");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 80, -1));

        ancho.setEnabled(false);
        ancho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchoActionPerformed(evt);
            }
        });
        getContentPane().add(ancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 120, 30));

        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 150, -1));

        jButton3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 140, -1));

        check1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check1MouseClicked(evt);
            }
        });
        getContentPane().add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        check2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check2MouseClicked(evt);
            }
        });
        getContentPane().add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        check3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check3MouseClicked(evt);
            }
        });
        getContentPane().add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        check4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check4MouseClicked(evt);
            }
        });
        getContentPane().add(check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        check5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check5MouseClicked(evt);
            }
        });
        getContentPane().add(check5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        check6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        check6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check6MouseClicked(evt);
            }
        });
        getContentPane().add(check6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        check7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check7MouseClicked(evt);
            }
        });
        getContentPane().add(check7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        check8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check8MouseClicked(evt);
            }
        });
        getContentPane().add(check8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        check9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check9MouseClicked(evt);
            }
        });
        getContentPane().add(check9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, -1));

        j.setBackground(new java.awt.Color(255, 255, 255));
        j.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/u.jpeg"))); // NOI18N
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1040, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar números.");
        }
    }//GEN-LAST:event_idKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Cualquier tipo de imagen", "jpg", "jpeg", "png");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(this);
        byte[] imagen;
        hp = chooser.getSelectedFile();

        imagen = AbrirArchivo(hp);
        ImageIcon i = new ImageIcon(imagen);
        Icon im = new ImageIcon(i.getImage().getScaledInstance(fotico.getWidth(), fotico.getHeight(), Image.SCALE_DEFAULT));
        fotico.setIcon(im);
        ci = true;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncActionPerformed

    }//GEN-LAST:event_ncActionPerformed

    private void edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadKeyTyped

    }//GEN-LAST:event_edadKeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Connection c = conexion();
        try {
            if (!id.equals("")) {
                if (!existencia(id.getText())) {
                    if (ci == true) {
                        ps = c.prepareStatement("INSERT INTO aguacates(id,zona,niveldecrecimiento,totalproducido,altura,ancho,edad,fechasiembra,fotoactual,fechafoto)VALUES(?,?,?,?,?,?,?,?,?,?)");
                        ps.setString(1, id.getText());
                        ps.setString(2, zona.getSelectedItem().toString());
                        ps.setString(3, nc.getText());
                        ps.setString(4, tp.getText());
                        ps.setString(5, altura.getText());
                        ps.setString(6, ancho.getText());
                        ps.setString(7, edad.getText());
                        ps.setString(8, fs.getDate().toString());
                        entrada = new FileInputStream(String.valueOf(hp));
                        ps.setBinaryStream(9, entrada);
                        ps.setString(10, fechafoto.getDate().toString());
                        int i = ps.executeUpdate();
                        ps.close();
                        if (i > 0) {
                            JOptionPane.showMessageDialog(null, "Se ha registrado el nuevo arbol de aguacate con id " + id.getText());
                            ps2 = c.prepareStatement("INSERT INTO fotos(foto,id,fechadelafoto,fechadesubida)VALUES (?,?,?,?)");
                            entrada = new FileInputStream(String.valueOf(hp));
                            ps2.setBinaryStream(1, entrada);
                            ps2.setString(2, id.getText());
                            ps2.setString(3, fechafoto.getDate().toString());
                            ps2.setString(4, fechactual());
                            ps2.executeUpdate();
                            ps2.close();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Necesitas poner una foto para este árbol.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ya el árbol con ese ID ha sido registrado");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Debes diligenciar todos los campos.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoArbol.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NuevoArbol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        menu m = new menu();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void anchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoActionPerformed

    private void check1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check1MouseClicked
        id.setEnabled(!id.isEnabled());
    }//GEN-LAST:event_check1MouseClicked

    private void check2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check2MouseClicked
        zona.setEnabled(!zona.isEnabled());
    }//GEN-LAST:event_check2MouseClicked

    private void check3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check3MouseClicked
        edad.setEnabled(!edad.isEnabled());
    }//GEN-LAST:event_check3MouseClicked

    private void check4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check4MouseClicked
        altura.setEnabled(!altura.isEnabled());
    }//GEN-LAST:event_check4MouseClicked

    private void check5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check5MouseClicked
        ancho.setEnabled(!ancho.isEnabled());
    }//GEN-LAST:event_check5MouseClicked

    private void check6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check6MouseClicked
        nc.setEnabled(!nc.isEnabled());
    }//GEN-LAST:event_check6MouseClicked

    private void check7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check7MouseClicked
        tp.setEnabled(!tp.isEnabled());
    }//GEN-LAST:event_check7MouseClicked

    private void check8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check8MouseClicked
        fs.setEnabled(!fs.isEnabled());
    }//GEN-LAST:event_check8MouseClicked

    private void check9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check9MouseClicked
        fechafoto.setEnabled(!fechafoto.isEnabled());
    }//GEN-LAST:event_check9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoArbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoArbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoArbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoArbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoArbol2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JTextField ancho;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JCheckBox check6;
    private javax.swing.JCheckBox check7;
    private javax.swing.JCheckBox check8;
    private javax.swing.JCheckBox check9;
    private javax.swing.JTextField edad;
    private com.toedter.calendar.JDateChooser fechafoto;
    private javax.swing.JLabel fotico;
    private com.toedter.calendar.JDateChooser fs;
    private javax.swing.JTextField id;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nc;
    private javax.swing.JTextField tp;
    private javax.swing.JComboBox<String> zona;
    // End of variables declaration//GEN-END:variables
}
