/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecohass;

import static ecohass.NuevoArbol.conexion;
import static ecohass.NuevoArbol.ps;
import static ecohass.Perfil.l1;
import static ecohass.Perfil.rr;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jaime
 */
public class VistaGeneral extends javax.swing.JFrame {

    /**
     * Creates new form VistaGeneral
     *
     * @param fruta
     */
    int ruta;

    public VistaGeneral(String fruta, int pr) throws SQLException {
        initComponents();
        Connection c = conexion();
        ruta = pr;
        int ancho = this.getWidth();
        int altura = this.getHeight();
        this.setExtendedState(MAXIMIZED_BOTH);
        if (fruta.equals("a")) {
            titulo.setText("Información de aguacates");
            titulo.setToolTipText("Debe seleccionar para que tipo de arbol hacer la consulta general.");
        } else {
            titulo.setText("Información de tomates de arbol");
        }
        titulo.setBounds((int) (ancho * 0.4), 50, (int) (ancho * 0.4), (int) (altura * 0.1));
        jTabbedPane1.setBounds((int) (ancho * 0.4), (int) (altura * 0.5), (int) (ancho * 0.8), (int) (altura * 0.2));
        int cont1 = 0, cont2 = 0, cont3 = 0, cont4 = 0, cont5 = 0;
        DefaultListModel l1, l2, l3, l4, l5, l6;
        l1 = new DefaultListModel();
        l2 = new DefaultListModel();
        l3 = new DefaultListModel();
        l4 = new DefaultListModel();
        l5 = new DefaultListModel();
        l6 = new DefaultListModel();
        ps = c.prepareStatement("SELECT id,zona FROM aguacates WHERE id > 0");
        rr = ps.executeQuery();
        while (rr.next()) {
            if (rr.getString("zona").equals("zona 1")) {
                l1.addElement(rr.getString("id"));
                cont1++;
            } else {
                if (rr.getString("zona").equals("zona 2")) {
                    l2.addElement(rr.getString("id"));
                    cont2++;
                } else {
                    if (rr.getString("zona").equals("zona 3")) {
                        l3.addElement(rr.getString("id"));
                        cont3++;
                    } else {
                        if (rr.getString("zona").equals("zona 4")) {
                            l4.addElement(rr.getString("id"));
                            cont4++;
                        } else {
                            l5.addElement(rr.getString("id"));
                            cont5++;
                        }
                    }
                }
            }
            l6.addElement(rr.getString("id"));
        }
        existentes1.setModel(l1);
        existentes2.setModel(l2);
        existentes3.setModel(l3);
        existentes4.setModel(l4);
        existentes5.setModel(l5);
        lg2.setModel(l6);
        existentestxt1.setText(existentestxt1.getText() + cont1);
        existentestxt2.setText(existentestxt2.getText() + cont2);
        existentestxt3.setText(existentestxt3.getText() + cont3);
        existentestxt4.setText(existentestxt4.getText() + cont4);
        existentestxt5.setText(existentestxt5.getText() + cont5);

        exgeneral.setText(exgeneral.getText() + (cont1 + cont2 + cont3 + cont4 + cont5));
    }

    private VistaGeneral() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jList21 = new javax.swing.JList<>();
        jScrollPane22 = new javax.swing.JScrollPane();
        existentes1 = new javax.swing.JList<>();
        jScrollPane23 = new javax.swing.JScrollPane();
        jList23 = new javax.swing.JList<>();
        jScrollPane24 = new javax.swing.JScrollPane();
        jList24 = new javax.swing.JList<>();
        jLabel53 = new javax.swing.JLabel();
        existentestxt1 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jList17 = new javax.swing.JList<>();
        jScrollPane18 = new javax.swing.JScrollPane();
        existentes2 = new javax.swing.JList<>();
        jScrollPane19 = new javax.swing.JScrollPane();
        jList19 = new javax.swing.JList<>();
        jScrollPane20 = new javax.swing.JScrollPane();
        jList20 = new javax.swing.JList<>();
        jLabel49 = new javax.swing.JLabel();
        existentestxt2 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList13 = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        existentes3 = new javax.swing.JList<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        jList15 = new javax.swing.JList<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        jList16 = new javax.swing.JList<>();
        jLabel45 = new javax.swing.JLabel();
        existentestxt3 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        existentes4 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList11 = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList12 = new javax.swing.JList<>();
        jLabel37 = new javax.swing.JLabel();
        existentestxt4 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        existentes5 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        existentestxt5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lg1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lg2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lg3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lg4 = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        exgeneral = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ECOHASS- FINCA LA ESPERANZA");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titulo.setText("VISTA GENERAL");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Arboles que no existen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Arboles enfermos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 25, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Arboles en buen estado de salud");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 25, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Arboles pertenecientes a este lote");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 25, -1, -1));

        jScrollPane21.setViewportView(jList21);

        jPanel1.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 380));

        jScrollPane22.setViewportView(existentes1);

        jPanel1.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 240, 380));

        jScrollPane23.setViewportView(jList23);

        jPanel1.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 230, 380));

        jScrollPane24.setViewportView(jList24);

        jPanel1.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 160, 380));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Cantidad total: ");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        existentestxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        existentestxt1.setText("Cantidad total: ");
        jPanel1.add(existentestxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 240, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Cantidad total: ");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 230, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Cantidad total: ");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 160, -1));

        jTabbedPane1.addTab("Lote 1", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Arboles pertenecientes a este lote");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 26, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Arboles en buen estado de salud");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 26, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Arboles que no existen");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Arboles enfermos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 26, -1, -1));

        jScrollPane17.setViewportView(jList17);

        jPanel2.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 400));

        jScrollPane18.setViewportView(existentes2);

        jPanel2.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 240, 400));

        jScrollPane19.setViewportView(jList19);

        jPanel2.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 240, 400));

        jScrollPane20.setViewportView(jList20);

        jPanel2.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 160, 400));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("Cantidad total: ");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, -1));

        existentestxt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        existentestxt2.setText("Cantidad total: ");
        jPanel2.add(existentestxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 240, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setText("Cantidad total: ");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 240, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("Cantidad total: ");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 160, -1));

        jTabbedPane1.addTab("Lote 2", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Arboles que no existen");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Arboles pertenecientes a este lote");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 25, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Arboles en buen estado de salud");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 25, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Arboles enfermos");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 25, -1, -1));

        jScrollPane13.setViewportView(jList13);

        jPanel3.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 380));

        jScrollPane14.setViewportView(existentes3);

        jPanel3.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 230, 380));

        jScrollPane15.setViewportView(jList15);

        jPanel3.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 230, 380));

        jScrollPane16.setViewportView(jList16);

        jPanel3.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 150, 380));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Cantidad total: ");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        existentestxt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        existentestxt3.setText("Cantidad total: ");
        jPanel3.add(existentestxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 230, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Cantidad total: ");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 230, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Cantidad total: ");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 150, -1));

        jTabbedPane1.addTab("Lote 3", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Arboles que no existen");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Arboles pertenecientes a este lote");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 25, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Arboles en buen estado de salud");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 25, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Arboles enfermos");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 25, -1, -1));

        jScrollPane9.setViewportView(jList9);

        jPanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 380));

        jScrollPane10.setViewportView(existentes4);

        jPanel4.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 230, 380));

        jScrollPane11.setViewportView(jList11);

        jPanel4.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 230, 380));

        jScrollPane12.setViewportView(jList12);

        jPanel4.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 170, 380));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Cantidad total: ");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        existentestxt4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        existentestxt4.setText("Cantidad total: ");
        jPanel4.add(existentestxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 230, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Cantidad total: ");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 230, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Cantidad total: ");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 170, -1));

        jTabbedPane1.addTab("Lote 4", jPanel4);

        jPanel5.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Arboles que no existen");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(10, 25, 157, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Arboles pertenecientes a este lote");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(209, 25, 233, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Arboles en buen estado de salud");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(480, 25, 224, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Arboles enfermos");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(744, 25, 121, 17);

        jScrollPane5.setViewportView(jList5);

        jPanel5.add(jScrollPane5);
        jScrollPane5.setBounds(10, 50, 170, 400);

        jScrollPane6.setViewportView(existentes5);

        jPanel5.add(jScrollPane6);
        jScrollPane6.setBounds(210, 50, 240, 400);

        jScrollPane7.setViewportView(jList7);

        jPanel5.add(jScrollPane7);
        jScrollPane7.setBounds(480, 50, 230, 400);

        jScrollPane8.setViewportView(jList8);

        jPanel5.add(jScrollPane8);
        jScrollPane8.setBounds(750, 50, 210, 400);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Cantidad total: ");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(10, 460, 170, 17);

        existentestxt5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        existentestxt5.setText("Cantidad total: ");
        jPanel5.add(existentestxt5);
        existentestxt5.setBounds(210, 460, 240, 17);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Cantidad total: ");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(490, 460, 220, 17);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Cantidad total: ");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(760, 460, 200, 17);

        jTabbedPane1.addTab("Lote 5", jPanel5);

        jPanel6.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Arboles que no existen");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(10, 25, 157, 17);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Arboles pertenecientes a este lote");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(209, 25, 233, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Arboles en buen estado de salud");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(480, 25, 224, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Arboles enfermos");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(744, 25, 121, 17);

        jScrollPane1.setViewportView(lg1);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 53, 157, 420);

        jScrollPane2.setViewportView(lg2);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(209, 61, 242, 410);

        jScrollPane3.setViewportView(lg3);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(490, 60, 224, 410);

        jScrollPane4.setViewportView(lg4);

        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(740, 60, 200, 410);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Cantidad total: ");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(10, 480, 190, 17);

        exgeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exgeneral.setText("Cantidad total: ");
        jPanel6.add(exgeneral);
        exgeneral.setBounds(210, 480, 240, 17);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Cantidad total: ");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(490, 480, 230, 17);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Cantidad total: ");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(740, 480, 200, 17);

        jTabbedPane1.addTab("General", jPanel6);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio n = new Inicio(ruta);
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /*try {
            Process p = Runtime.getRuntime().exec("C:\\xampp\\xampp_stop");
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_formWindowClosing

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exgeneral;
    private javax.swing.JList<String> existentes1;
    private javax.swing.JList<String> existentes2;
    private javax.swing.JList<String> existentes3;
    private javax.swing.JList<String> existentes4;
    private javax.swing.JList<String> existentes5;
    private javax.swing.JLabel existentestxt1;
    private javax.swing.JLabel existentestxt2;
    private javax.swing.JLabel existentestxt3;
    private javax.swing.JLabel existentestxt4;
    private javax.swing.JLabel existentestxt5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList11;
    private javax.swing.JList<String> jList12;
    private javax.swing.JList<String> jList13;
    private javax.swing.JList<String> jList15;
    private javax.swing.JList<String> jList16;
    private javax.swing.JList<String> jList17;
    private javax.swing.JList<String> jList19;
    private javax.swing.JList<String> jList20;
    private javax.swing.JList<String> jList21;
    private javax.swing.JList<String> jList23;
    private javax.swing.JList<String> jList24;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lg1;
    private javax.swing.JList<String> lg2;
    private javax.swing.JList<String> lg3;
    private javax.swing.JList<String> lg4;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
